version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update && apt-get install -y zip

  build:
    commands:
      - echo "Zipping entire project directory..."
      - zip -r lambda.zip . -x ".git/*" ".github/*" "lambda.zip"
      - echo "Deploying zipped package to Lambda..."
      - |
        aws lambda update-function-code \
          --function-name lambda_check \
          --zip-file fileb://lambda.zip

artifacts:
  files:
    - lambda.zip
