name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package Lambda code
        run: |
          mkdir build
          cp app.py build/
          cd build && zip -r ../lambda.zip .

      - name: Deploy to Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          function_name: lambda_check
          zip_file: lambda.zip
